import type { Metadata } from "next";

import { WithBreadcrumbs } from "@/components/with-breadcrumbs";

export const metadata: Metadata = {
  title: "FAQ - Frequently Asked Questions | WebsiteKit",
  description:
    "Get answers to common questions about WebsiteKit tools, including meta tag generation, QR codes, favicons, and more.",
  alternates: {
    canonical: "/faq",
  },
  openGraph: {
    title: "FAQ - Frequently Asked Questions | WebsiteKit",
    description:
      "Get answers to common questions about WebsiteKit tools.",
    url: "/faq",
    siteName: "WebsiteKit",
    type: "website",
  },
  twitter: {
    card: "summary",
    title: "FAQ - Frequently Asked Questions | WebsiteKit",
    description:
      "Get answers to common questions about WebsiteKit tools.",
  },
};

function JsonLd({ data }: { data: unknown }) {
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}

const faqItems = [
  {
    question: "Is WebsiteKit really free?",
    answer:
      "Yes! All tools on WebsiteKit are completely free to use. No signup, no credit card, no hidden fees. We believe essential web development tools should be accessible to everyone.",
  },
  {
    question: "Do I need to create an account?",
    answer:
      "No account is required. All tools work instantly in your browser. Your website assets are saved locally in your browser's storage for convenience.",
  },
  {
    question: "Is my data stored on your servers?",
    answer:
      "No. All processing happens in your browser. Your website data, logos, and generated outputs are never sent to our servers. Everything stays local.",
  },
  {
    question: "What tools are available?",
    answer:
      "WebsiteKit offers tools for meta tag generation, QR code creation, favicon generation, sitemap building, security headers, and more. We're constantly adding new tools.",
  },
  {
    question: "Can I use the generated code in commercial projects?",
    answer:
      "Absolutely! All outputs generated by WebsiteKit tools are yours to use however you like, including in commercial projects. No attribution required.",
  },
  {
    question: "How do I report a bug or suggest a feature?",
    answer:
      "We'd love to hear from you! Visit our Contact page to send us feedback, report bugs, or suggest new tools and features.",
  },
];

function buildFaqJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: faqItems.map((item) => ({
      "@type": "Question",
      name: item.question,
      acceptedAnswer: {
        "@type": "Answer",
        text: item.answer,
      },
    })),
  };
}

export default function FAQPage() {
  return (
    <WithBreadcrumbs
      breadcrumbs={[
        { label: "Home", href: "/" },
        { label: "FAQ", href: "/faq" },
      ]}
    >
      <JsonLd data={buildFaqJsonLd()} />
      <div className="max-w-2xl space-y-8">
        <header className="space-y-2">
          <h1 className="text-3xl font-bold tracking-tight">
            Frequently Asked Questions
          </h1>
          <p className="text-muted-foreground">
            Everything you need to know about WebsiteKit and our tools.
          </p>
        </header>

        <div className="space-y-6">
          {faqItems.map((item, index) => (
            <article
              key={index}
              className="rounded-lg border bg-card p-5 space-y-2"
            >
              <h2 className="font-semibold text-lg">{item.question}</h2>
              <p className="text-muted-foreground">{item.answer}</p>
            </article>
          ))}
        </div>

        <div className="rounded-lg border bg-muted/30 p-5">
          <h2 className="font-semibold">Still have questions?</h2>
          <p className="text-sm text-muted-foreground mt-1">
            Can&apos;t find what you&apos;re looking for? Feel free to{" "}
            <a href="/contact" className="underline hover:text-foreground">
              contact us
            </a>{" "}
            and we&apos;ll get back to you as soon as possible.
          </p>
        </div>
      </div>
    </WithBreadcrumbs>
  );
}
